FROM php:latest

RUN apt-get update && apt-get install -y curl gnupg build-essential

RUN curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o /usr/local/bin/n && \
    chmod +x /usr/local/bin/n && \
    n latest

WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./

RUN npm install

COPY src ./src
COPY public ./public

RUN npm run build && mkdir -p /var/www/html/js && cp dist/index.js /var/www/html/js/index.js

EXPOSE 3000
