version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASS: password
      DB_NAME: mydatabase
    # volumes:
    #   - ./app:/var/www/html  # Your unified app source

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  db_data:
