services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./public/index.php:/var/www/html/index.php
      - ./php:/var/www/html/php
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm run dev & php -S 0.0.0.0:3000 -t /var/www/html"
