services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    volumes:
      - ./src:/server/src
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start
