services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: my-app
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./public:/var/www/html/php
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm run dev & php -S 0.0.0.0:3000 -t /var/www/html"
