services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: my-app
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.php:/app/index.php
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
