FROM php:latest

RUN apt-get update && apt-get install -y curl gnupg build-essential

RUN curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o /usr/local/bin/n && \
    chmod +x /usr/local/bin/n && \
    n latest

RUN npm install -g npm

WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./

RUN npm install

COPY src ./src
COPY public ./public

RUN npm run build && cp dist/index.js /var/www/html/index.js && cp public/index.php /var/www/html/index.php

EXPOSE 3000

CMD ["php", "-S", "0.0.0.0:3000", "-t", "/var/www/html"]
